name: Deploy em Ambientes
description: Atualiza ambientes com as branches passadas
title: '[Deployment]: '
labels: ['environment-deploy']
body:
  - type: input
    id: branches
    attributes:
      label: Branches
      description: Você pode optar em passar uma só branch ou várias separadas por virgula
      placeholder: branch-1,branch-2
    validations:
      required: true

  - type: checkboxes
    id: environments
    attributes:
      label: Ambientes
      options:
        - label: Develop
        - label: Homolog
        - label: Staging
