name: Deploy to Environments
description: Update environments with sent branches
title: '[Deployment]: '
labels: ['environment-deploy']
body:
  - type: input
    id: branches
    attributes:
      label: Branches
      description: You can choose to send only one branch or more than one, in this case you need to write separating the names with a comma
      placeholder: branch-1,branch-2
    validations:
      required: true

  - type: checkboxes
    id: shouldDelete
    attributes:
      label: Remove
      description: You can remove a branch from the environment
      options:
        - label: remove branch

  - type: checkboxes
    id: environments
    attributes:
      label: Environments
      options:
        - label: Develop
        - label: Homolog
        - label: Staging
