name: Relatório de incidente
description: Arquivo de relatório de incidente
title: '[Incident]: '
labels: ['incident']
body:
  - type: markdown
    attributes:
      value: Preencha os campos abaixo para registrar o incidente de deployment!
  - type: input
    id: squad
    attributes:
      label: Nome da Squad
      description: Qual o nome da sua squad?
      placeholder: ex. Squad Busca
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: O quê aconteceu?
      description: Diga de forma resumida qual foi o incidente?
      placeholder: Insira aqui o resumo!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Evidencias relevantes
      description: Insira as evidências relevantes relacionadas ao incidente.
      render: shell
  - type: input
    id: rca
    attributes:
      label: Causa Raíz
      description: Se o commit que gerou o erro foi identificado informe o seu Hash?
      placeholder: ex. cd6bd9dd5b95cbea2d2470b8c788bfd06d44c011
    validations:
      required: false
