name: Handle environments secrets
description: Manage environment variables in vault
title: '[Manage env vars]: '
labels: ['mange-env-vars']
body:
  - type: input
    id: var-name
    attributes:
      label: Env name
      description: You need to send the env name to be updated or deleted.
      placeholder: gitHubUser
    validations:
      required: true

  - type: input
    id: var-value
    attributes:
      label: Env value
      description: To create or update an env var send this value is required.
      placeholder: octoCat

  - type: checkboxes
    id: var-environments
    attributes:
      label: Environments
      description: To create or update an env var send this value is required.
      options:
        - label: dev-environment
        - label: qa-environment
        - label: uat1-environment

  - type: checkboxes
    id: var-delete
    attributes:
      label: This env var need to be deleted?
      description: If you want to delete a variable, please check this option.
      options:
        - label: delete
