name: Handle environments secrets
description: Manage environment variables in vault
title: '[Manage env vars]: '
labels: ['mange-env-vars']
body:
  - type: input
    id: var-values
    attributes:
      label: Env value
      description: |
        To create or update an env var send this value is required. To avoid doubts about the processing of sending values without blanks

        ⚠️ Attention, pattern for sending envs:  gitHubUser=octoCat,appName=myApp
      placeholder: gitHubUser=octoCat,gitHubUserEmail=octoCat@github.com

  - type: checkboxes
    id: var-environments
    attributes:
      label: Environments
      description: To create or update an env var send this value is required.
      options:
        - label: dev-environment
        - label: qa-environment
        - label: uat1-environment
        - label: prod-environment

  - type: checkboxes
    id: var-delete
    attributes:
      label: This env var need to be deleted?
      description: If you want to delete a variable, please check this option.
      options:
        - label: delete
