name: Deploy by issue
description: Create a new deploy in develop environments
labels: ["deploy-develop"]
body:
  - type: input
    id: branch-name
    attributes:
      label: Nome da branch
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: O Deploy deve ser feito em qual ambiente?
      multiple: true
      options:
        - Develop
        - Homolog
  - type: textarea
    id: description
    attributes:
      label: Descrição
