name: Manage vault secrets
permissions: write-all

on:
  workflow_call:

jobs:
  set-env:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Install Vault CLI
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install vault

      - name: Authenticate with Vault
        run: vault login 85858

      - name: Set Vault Environment Variable
        env:
          VAULT_ADDR: https://vault.factory.adeo.cloud
        run: vault write secret/my-secrets/my-app NEW_ENV_VAR="new-value"
